export const SEARCH_MOVIE = 'SEARCH_MOVIE'
export const SEARCH_MOVIE_ERROR = 'SEARCH_MOVIE_ERROR'
export const SEARCH_MOVIE_LOADING = 'SEARCH_MOVIE_LOADING'

export const CLEAR_MOVIE_LIST = 'CLEAR_MOVIE_LIST'
export const SELECT_MOVIE = 'SELECT_MOVIE'

export const SAVE_FAV_MOVIE = "SAVE_FAV_MOVIE"
export const LOAD_FAV_MOVIE = "LOAD_FAV_MOVIE"

